name: "CI"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "osiris-0"
      - "osiris-1"
  push:
    branches:
      - "osiris-0"
      - "osiris-1"
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out"
        uses: "actions/checkout@v4"
      - name: "GCP auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Java"
        uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "gradle"
      - name: "Gradle classes"
        run: |
          ./gradlew classes testClasses
      - name: "Gradle test"
        run: |
          ./gradlew test
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
      - name: "Gradle detekt"
        run: |
          ./gradlew detektMain detektTest
